---
title: "benchmarking"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      toc_levels: 2
    number_sections: true
    highlight: zenburn
    code_folding: show
    fig_caption: true
    df_print: paged 
---

<style>
p.caption {
  font-size: 0.6em;
  text-align: "center";
}



# Introduction

This vignette presents a benchmarking analysis comparing the performance of functions from the `fio` package with equivalent base R functions. The `fio` package provides a set of functions for input-output analysis, a method used in economics to analyze the interdependencies between different sectors of an economy.

In this document, we will focus on two key functions: the technical coefficients matrix calculation and the Leontief inverse matrix calculation. These functions are fundamental to input-output analysis, and their performance can significantly impact the speed of larger analyses.

Our benchmarking tests, which involve running these functions repeatedely in simulated datasets, show that the `fio` package functions are faster than the equivalent base R functions. This improved performance can make a substantial difference in larger analyses, making the `fio` package a valuable tool for input-output analysis in R.

The tests were run on a simulated $2000 \times 2000$ matrix, and each test was repeated 100 times to account for variability. Please note that the results of this benchmarking analysis are dependent on the specific test datasets used and the hardware on which the algorithms were run. Therefore, the results should be interpreted in the context of these specific conditions.

## Technical coefficients matrix

The technical coefficients matrix calculation, a key and initial step in input-output analysis, was tested using the `compute_tech_coeff()` function from the `{fio}` package, equivalent functions from the `{leontief}` package, and a base R implementation. It consists on dividing each $a_{ij}$ element of intermediate transactions matrix by the correspondent $x_j$ element of total production vector^[Or in a equivalent way, multiplying intermediate transactions matrix by a diagonal matrix constructed from total production vector.]. The results show that both `{fio}` and `{leontief}` functions execute almost instantaneously, with `{fio}` slightly faster (about 5 milliseconds apart). In contrast, the base R implementation is about 150 times slower than `{fio}`.


```r
# set seed
set.seed(100)

# data
matrix_dim <- 2000
intermediate_transactions <- matrix(
  as.double(sample(1:1000, matrix_dim^2, replace = TRUE)),
  nrow = matrix_dim,
  ncol = matrix_dim
)
total_production <- matrix(
  as.double(sample(4000000:6000000, matrix_dim, replace = TRUE)),
  nrow = 1,
  ncol = matrix_dim
)

# Base R function
tech_coeff_r <- function(intermediate_transactions, total_production) {
  tech_coeff_matrix <- intermediate_transactions %*% diag(1 / as.vector(total_production))
  return(tech_coeff_matrix)
}

# {fio} setup
iom_fio <- fio::iom$new("iom", intermediate_transactions, total_production)
#> Error in loadNamespace(x): there is no package called 'fio'

# benchmark
benchmark_a <- microbenchmark::microbenchmark(
  fio = fio:::compute_tech_coeff(intermediate_transactions, total_production),
  `Base R` = tech_coeff_r(intermediate_transactions, total_production),
  leontief = leontief::input_requirement(intermediate_transactions, total_production),
  times = 100
)
#> Error in loadNamespace(x): there is no package called 'fio'
print(benchmark_a)
#> Error in eval(expr, envir, enclos): object 'benchmark_a' not found

# plot
ggplot2::autoplot(benchmark_a)
#> Error in loadNamespace(x): there is no package called 'ggplot2'
```

## Leontief inverse matrix

When we're talking about inverting a $2000 \times 2000$ there's a lot more work involved. Leontief matrix ($B$) is obtained from subtracting the technical coefficients matrix ($A$) from the identity matrix ($I$), therefore it has no null rows or columns. 

$$B = I - A$$

It allows for solving the linear system through LU decomposition, which is a more efficient method than the direct inverse matrix calculation. `{fio}` takes advantage of LU decomposition and becomes incredibly faster, while `{leontief}` is over 10 times slower, followed closed by the over 20 times slower base R implementation. 


```r
# data
iom_fio$compute_tech_coeff()
#> Error in eval(expr, envir, enclos): object 'iom_fio' not found
technical_coefficients_matrix <- iom_fio$technical_coefficients_matrix
#> Error in eval(expr, envir, enclos): object 'iom_fio' not found

# base R function
leontief_inverse_r <- function(technical_coefficients_matrix) {
  dim <- nrow(technical_coefficients_matrix)
  leontief_inverse_matrix <- solve(diag(dim) - technical_coefficients_matrix)
  return(leontief_inverse_matrix)
}

# benchmark
benchmark_b <- microbenchmark::microbenchmark(
  fio = fio:::compute_leontief_inverse(technical_coefficients_matrix),
  `Base R` = leontief_inverse_r(technical_coefficients_matrix),
  leontief = leontief::leontief_inverse(technical_coefficients_matrix),
  times = 100
)
#> Error in loadNamespace(x): there is no package called 'fio'
print(benchmark_b)
#> Error in eval(expr, envir, enclos): object 'benchmark_b' not found

# plot
ggplot2::autoplot(benchmark_b)
#> Error in loadNamespace(x): there is no package called 'ggplot2'
```

## Sensitivity of dispersion coefficients of variation

To represent linkage-based functions performance, we compute benchmark for sensitivity of dispersion coefficients of variation. All 3 implementations executes almost instantaneously, with `{fio}` being slightly slower than `{leontief}` and base R functions. 


```r
# data
iom_fio$compute_leontief_inverse()
#> Error in eval(expr, envir, enclos): object 'iom_fio' not found
leontief_inverse_matrix <- iom_fio$leontief_inverse_matrix
#> Error in eval(expr, envir, enclos): object 'iom_fio' not found

# base R function
sensitivity_r <- function(B) {
  n <- nrow(B)
  SL = rowSums(B)
  ML = SL / n
  (((1 / (n - 1)) * (colSums((B - ML) ** 2))) ** 0.5) / ML
}

# benchmark
benchmark_c <- microbenchmark::microbenchmark(
  fio = fio:::compute_sensitivity_dispersion_cv(leontief_inverse_matrix),
  `Base R` = sensitivity_r(leontief_inverse_matrix),
  leontief = leontief::sensitivity_dispersion_cv(leontief_inverse_matrix),
  times = 100
)
#> Error in eval(expr, envir, enclos): object 'leontief_inverse_matrix' not found
print(benchmark_c)
#> Error in eval(expr, envir, enclos): object 'benchmark_c' not found
ggplot2::autoplot(benchmark_c)
#> Error in loadNamespace(x): there is no package called 'ggplot2'
```

# Field of influence

Since field of influence involves computing Leontief inverse matrix for each element of technical coefficients matrix after an increment, it can be demanding for high dimensional matrices. Here, we evaluate benchmark for base R function and {fio}, since there's no similiar function in {leontief}. For brevity, we cut dimensions to 100 and repetitions to 10.

{fio} is, again, much faster than base R, even for small matrices. Note that for larger matrices, that difference would greatly increase. 


```r
# data
matrix_dim <- 100
intermediate_transactions <- matrix(
  as.double(sample(1:1000, matrix_dim^2, replace = TRUE)),
  nrow = matrix_dim,
  ncol = matrix_dim
)
total_production <- matrix(
  as.double(sample(4000000:6000000, matrix_dim, replace = TRUE)),
  nrow = 1,
  ncol = matrix_dim
)
iom_fio_reduced <- fio::iom$new(
  "iom_reduced",
  intermediate_transactions,
  total_production
)$compute_tech_coeff()$compute_leontief_inverse()
#> Error in loadNamespace(x): there is no package called 'fio'

# base R function
field_influence_r <- function(A, B, ee = 0.001) {
  n = nrow(A)
  I = diag(n)
  E = matrix(0, ncol = n, nrow = n)
  SI = matrix(0, ncol = n, nrow = n)
  for (i in 1:n) {
    for (j in 1:n) {
      E[i, j] = ee
      AE = A + E
      BE = solve(I - AE)
      FE = (BE - B) / ee
      FEq = FE * FE
      S = sum(FEq)
      SI[i, j] = S
      E[i, j] = 0
    }
  }
}

# benchmark
benchmark_d <- microbenchmark::microbenchmark(
  fio = fio:::compute_field_influence(
    iom_fio_reduced$technical_coefficients_matrix,
    iom_fio_reduced$leontief_inverse_matrix,
    0.001
  ),
  `Base R` = field_influence_r(iom_fio_reduced$technical_coefficients_matrix, iom_fio_reduced$leontief_inverse_matrix),
  times = 10
)
#> Error in eval(expr, envir, enclos): object 'iom_fio_reduced' not found
print(benchmark_d)
#> Error in eval(expr, envir, enclos): object 'benchmark_d' not found
ggplot2::autoplot(benchmark_d)
#> Error in loadNamespace(x): there is no package called 'ggplot2'
```
