# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fio_wrappers", use_symbols = TRUE, package_name = "fio")

#' @docType package
#' @usage NULL
#' @useDynLib fio, .registration = TRUE
NULL

#' Calculates technical coefficients matrix to R.
#' @param intermediate_transactions A nxn matrix of intermediate transactions.
#' @param total_production A 1xn vector of total production.
#' @return A nxn matrix of technical coefficients, known as A matrix.
#' @export
tec_coeff <- function(intermediate_transactions, total_production) .Call(wrap__tec_coeff, intermediate_transactions, total_production)

leontief_inverse <- function(tec_coeff) .Call(wrap__leontief_inverse, tec_coeff)


# nolint end
