# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fio_wrappers", use_symbols = TRUE, package_name = "fio")

#' @docType package
#' @usage NULL
#' @useDynLib fio, .registration = TRUE
NULL

#' Calculates technical coefficients matrix to R.
#' @param intermediate_transactions A nxn matrix of intermediate transactions.
#' @param total_production A 1xn vector of total production.
#' @return A nxn matrix of technical coefficients, known as A matrix.
#' @examples
#' intermediate_transactions <- matrix(c(1, 2, 3, 4), nrow = 2)
#' total_production <- c(10, 20)
#' tec_coeff(intermediate_transactions, total_production)
#' @export
tec_coeff <- function(intermediate_transactions, total_production) .Call(wrap__tec_coeff, intermediate_transactions, total_production)

#' Calculates Leontief inverse matrix to R.
#' @param tec_coeff A nxn matrix of technical coefficients.
#' @return A nxn matrix of Leontief inverse.
#' @examples
#' tec_coeff <- matrix(c(0.1, 0.2, 0.3, 0.4), nrow = 2)
#' leontief_inverse(tec_coeff)
#' @export
leontief_inverse <- function(tec_coeff) .Call(wrap__leontief_inverse, tec_coeff)


# nolint end
