# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fio_wrappers", use_symbols = TRUE, package_name = "fio")

#' @docType package
#' @usage NULL
#' @useDynLib fio, .registration = TRUE
NULL

#' Computes technical coefficients matrix to R.
#' @param intermediate_transactions A nxn matrix of intermediate transactions.
#' @param total_production A 1xn vector of total production.
#' @return A nxn matrix of technical coefficients, known as A matrix.
compute_tech_coeff <- function(intermediate_transactions, total_production) .Call(wrap__compute_tech_coeff, intermediate_transactions, total_production)

#' Computes Leontief inverse matrix to R.
#' @param tech_coeff A nxn matrix of technical coefficients.
#' @return A nxn matrix of Leontief inverse.
compute_leontief_inverse <- function(tech_coeff) .Call(wrap__compute_leontief_inverse, tech_coeff)

#' Calculates output multiplier.
#' @param leontief_inverse_matrix The open model Leontief inverse matrix.
#' @return A 1xn vector of output multipliers.
compute_multiplier_output <- function(leontief_inverse_matrix) .Call(wrap__compute_multiplier_output, leontief_inverse_matrix)

#' Calculates field of influence given a technical change.
#' @param tech_coeff_matrix A nxn matrix of technical coefficients.
#' @param leontief_inverse_matrix The open model nxn Leontief inverse matrix.
#' @param epsilon The epsilon value.
#' @description
#' Calculates total field of influence given a incremental change in the techincal coefficients matrix.
#' @return Field of influence matrix.
compute_field_influence <- function(tech_coeff_matrix, leontief_inverse_matrix, epsilon) .Call(wrap__compute_field_influence, tech_coeff_matrix, leontief_inverse_matrix, epsilon)

#' Computes foward linkages
#' @param leontief_inverse_matrix A nxn matrix of Leontief inverse.
#' @description
#' Computes forward linkages from a Leontief inverse matrix.
#' @return A vector of forward linkages.
compute_forward_linkages <- function(leontief_inverse_matrix) .Call(wrap__compute_forward_linkages, leontief_inverse_matrix)

#' Computes backward linkages
#' @param leontief_inverse_matrix A nxn matrix of Leontief inverse.
#' @description
#' Computes backward linkages from a Leontief inverse matrix.
#' @return A vector of backward linkages.
compute_backward_linkages <- function(leontief_inverse_matrix) .Call(wrap__compute_backward_linkages, leontief_inverse_matrix)

#' Computes power of dispersion coefficients of variation
#' @param leontief_inverse_matrix A nxn matrix of Leontief inverse.
#' @description
#' Computes power of dispersion coefficients of variation of an economy.
#' @return A vector of power of dispersion coefficients of variation.
compute_power_dispersion <- function(leontief_inverse_matrix) .Call(wrap__compute_power_dispersion, leontief_inverse_matrix)

#' Computes sensitivity of dispersion coefficients of variation
#' @param leontief_inverse_matrix A nxn matrix of Leontief inverse.
#' @description
#' Computes sensitivity of dispersion coefficients of variation of an economy.
#' @return A vector of sensitivity of dispersion coefficients of variation.
compute_sensitivity_dispersion <- function(leontief_inverse_matrix) .Call(wrap__compute_sensitivity_dispersion, leontief_inverse_matrix)


# nolint end
