# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    
name: Rust-check

permissions: read-all

jobs:
  no-install:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    container:
      image: fedora:40

    steps:
      - uses: actions/checkout@v4

      - name: Install Fedora dependencies
        run: |
          sudo dnf install -y libxml2-devel libcurl-devel harfbuzz-devel fribidi-devel openssl-devel freetype-devel libpng-devel libtiff-devel libjpeg-devel qpdf xz devscripts glibc-langpack-en pandoc
      - name: Setup R
        run: |
          sudo dnf install -y R
          # install R packages
          R -e 'install.packages(c("remotes", "rcmdcheck", "emoji", "Rdpack", "readxl", "clipr", "fs", "miniUI", "shiny", "knitr", "rmarkdown", "spelling", "microbenchmark", "leontief", "ggplot2", "writexl", "testthat"), repos = "http://cloud.r-project.org")'
      - name: Build package
        id: check_no_install
        continue-on-error: true
        run: |
          R CMD build .
      - name: Fail if check succeeds
        if: steps.check_no_install.outcome == 'success'
        run: |
          echo "Package builds, but it should have failed because Rust is not installed."
          exit 1
      - name: Mark as success if failure was expected
        if: steps.check_no_install.outcome == 'failure'
        run: echo "Build fails as expected."
  
  msrv-lower:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    container:
      image: fedora:40

    steps:
      - uses: actions/checkout@v4

      - name: Install Fedora dependencies
        run: |
          sudo dnf install -y libxml2-devel libcurl-devel harfbuzz-devel fribidi-devel openssl-devel freetype-devel libpng-devel libtiff-devel libjpeg-devel qpdf xz devscripts glibc-langpack-en pandoc
      - name: Install and set Rust toolchain to 1.66.0
        run: |
          # download and install rust
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          # add cargo to PATH
          . "$HOME/.cargo/env"
          # set default toolchain
          rustup default 1.66
      
      - name: Setup R
        run: |
          sudo dnf install -y R
          # install R packages
          R -e 'install.packages(c("remotes", "rcmdcheck", "emoji", "Rdpack", "readxl", "clipr", "fs", "miniUI", "shiny", "knitr", "rmarkdown", "spelling", "microbenchmark", "leontief", "ggplot2", "writexl", "testthat"), repos = "http://cloud.r-project.org")'
      - name: Build package
        id: check_lower
        continue-on-error: true
        run: |
          R CMD build .
      - name: Fail if check succeeds
        if: steps.check_lower.outcome == 'success'
        run: |
          echo "Package builds, but it should have failed because the version of Rust is lower than MSRV."
      - name: Mark as success if failure was expected
        if: steps.check_lower.outcome == 'failure'
        run: echo "Build fails as expected."
